services:
  mysql-mcp-server:
    container_name: mysql-mcp-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6277:6277"
    volumes:
      - ../:/workspace:cached
    working_dir: /workspace
    command: sleep infinity

networks:
  default:
    name: dev_default
    external: true
